development

diff --git a/.github/workflows/pip_install.yml b/.github/workflows/pip_install.yml
--- a/.github/workflows/pip_install.yml
+++ b/.github/workflows/pip_install.yml
@@ -32,10 +32,10 @@ jobs:
           pip install .
         continue-on-error: true  # Allow the job to continue even if installation fails
 
-      - name: Run tests
-        run: |
-          pytest --maxfail=1 --disable-warnings -q || exit 1  # Fail this step if tests fail
-        continue-on-error: true  # Allow the job to continue even if tests fail
+      # - name: Run tests
+      #   run: |
+      #     pytest --maxfail=1 --disable-warnings -q || exit 1  # Fail this step if tests fail
+      #   continue-on-error: true  # Allow the job to continue even if tests fail
 
       - name: Output result
         run: |
