development

diff --git a/.github/workflows/summarise.yml b/.github/workflows/summarise.yml
--- a/.github/workflows/summarise.yml
+++ b/.github/workflows/summarise.yml
@@ -77,11 +77,11 @@ jobs:
           # Remove JSON files starting with repo name
           find ${{inputs.output-path}} -type f -name "${REPO_LOWER}_*.json" -exec rm -v {} \;
 
-          # Only commit if there are changes
-          if ! git diff --quiet --exit-code; then
-            git add -A 
-            git commit -m 'Automated Cleanup'
-          fi
+          # # Only commit if there are changes
+          # if ! git diff --quiet --exit-code; then
+          #   git add -A 
+          #   git commit -m 'Automated Cleanup'
+          # fi
           
         shell: bash
 
@@ -97,7 +97,7 @@ jobs:
       - name: Commit and Push Changes
         uses: EndBug/add-and-commit@v9
         with:
-          add: '${{inputs.output-path}}*'
+          add: '${{inputs.output-path}}'
           author_name: ${{ github.actor }}
           author_email: ${{ github.actor }}@users.noreply.github.com
           message: 'Automated summary generate from src-data branch.'
